hebrew_quiz/urls.py
from django.conf.urls import patterns, url

from hebrew_quiz import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^a=(?P<guess>\d+)/$', views.answer, name='answer'),
    url(r'^cat=(?P<cat>\d+)/$', views.setCategory, name='setCategory'),
    url(r'^showCat=(?P<showCat>\d+)/$', views.showCategories, name='showCategories'),
    url(r'^help=(?P<help>\d+)/$', views.showHelp, name='showHelp'),
)

moreh/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'moreh.views.home', name='home'),
    url(r'^$', 'hebrew_quiz.views.index', name='index'),
    # url(r'^moreh/', include('moreh.foo.urls')),
	url(r'^hebrew_quiz/', include('hebrew_quiz.urls', namespace='hebrew_quiz')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),
)

hebrew_quiz/models.py
"""
    hebrew_quiz.models
    ===================

https://developers.google.com/appengine/docs/python/datastore/overview
Limit                                                       Amount
Maximum entity size                                         1 megabyte
Maximum transaction size                                     10 megabytes
Maximum number of index entries for an entity                 20000
Maximum number of bytes in composite indexes for an entity     2 megabytes
"""
from django.db import models
#from google.appengine.ext import db

def update_model(model, d={}):
    # add model parameters based on a dictionary
    # updating models is an inline change
    for k, v in values.iteritems():
        setattr(model, k, v)        

class Question(models.Model):
    #q, a_opt, a_shift = Quiz.question()
    #s_question = db.StringProperty(required=True)
    #sl_answers = db.StringListProperty(required=True)
    #i_rotate   = db.IntegerProperty(required=True)
    s_question = models.CharField(max_length=100)
    sl_answers = models.CharField(max_length=100)
    i_rotate   = models.PositiveSmallIntegerField()
    
    def __unicode__(self):
        return self.s_question
    

hebrew_quiz/views.py
# Create your views here.
from datetime import datetime as dt

from code.Moreh import *
# Imports these objects
# h = HebrewReference()
# qz = Quiz(test=0)
      
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render_to_response

class Choice(collections.namedtuple('Choice',['idx','a'])):
    pass
    
def makeChoices(options):
    return [ Choice(i, s) for i,s in enumerate(options) ]

class Category(collections.namedtuple('Category',['name','done','idx','progress'])):
    pass
    
def makeCategories():
    categories = []
    for i, s in enumerate(qz.sets):
        set_progress, num_left = qz.progress(s[1])
        categories += [ Category(s[1].name, (set_progress == 100), i, qz.progress(s[1])) ]
    #return [ Category(*tuple([s[1].name]+list(qz.progress(s[1])))) for s in qz.sets ]
    return categories

# TODO: create global response dictionary, update it from the view methods, 
# and use global dictionary in the render_to_response call (use decorator?)
quiz_params = {
    'html':'index.html',
    'now': dt.now(),

    'question': None,
    'choices': makeChoices(['A','B','C','D']),

    'feedback': False,
    'correct': False,
    'previous': None,
    'progress': None,

    'show_cat': True,
    'categories': makeCategories(),

    'show_help': True,
    'q_set': qz.q_set,
    }

def getQuestion():
    q = qz.question()
    if qz.q_set != quiz_params['q_set']:
        quiz_params.update({'feedback': False, 'show_help':True})
    quiz_params.update({'question': q, 'q_set': qz.q_set,
        'choices': makeChoices(q.options)})    

# Get question to start things out
getQuestion()

def render(params={}, request=None):
    params['now'] = dt.now()
    return render_to_response(params['html'], params, context_instance=RequestContext(request))
    
def index(request):
    getQuestion()
    quiz_params.update({'feedback': False})
    return render(quiz_params, request)
	
def answer(request, guess):
    old_q, correct, progress = qz.answer(int(guess))
    quiz_params.update({'feedback': True, 'correct': correct, 'previous': old_q,
        'progress': '{0:2d}%'.format(int(progress)),
        'categories': makeCategories()})
    
    getQuestion()    
    return render(quiz_params, request)

###########################################################

def showCategories(request, showCat):
    quiz_params.update({'show_cat': bool(int(showCat))})
    return render(quiz_params, request)

###########################################################

def showHelp(request, help):
    qz.penalty()
    quiz_params.update({'feedback': False, 'show_help': bool(int(help)), 
        'q_set': qz.q_set, 'categories': makeCategories()})
    return render(quiz_params, request)

###########################################################

def setCategory(request, cat):
    qz.setCategory(int(cat))    

    # get a new question from the selected set
    getQuestion()    

    return showHelp(request, '1')
    

templates/hebrew_quiz/index.html
{% load staticfiles %}
<html>
<head>
    <title>{% block head_title %}Moreh{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hebrew_quiz/quiz.css' %}" />
    <link rel="shortcut icon" href="{% static 'hebrew_quiz/aleph.ico' %}">
</head>
<body>    
<div class="wrapper">
    <div class="header"><p>{{ question.name }}</p></div>
    <div class="main">
        {% if show_help %}
            <div class="help">
                <p style="width:300px;">Return to this screen by clicking the "Cheat" button below. Note that this will set you back a few questions!</p>
                <table>
                    {% for i in q_set %}
                        <tr><td style="font-size:xx-large;">{{ i.q }}</td><td>{{ i.a }}</td></tr>
                    {% endfor %}
                </table>                
                <p><a href="{% url 'hebrew_quiz:showHelp' 0 %}">Done</a></p>
            </div>
        {% else %}
            <div class="q_feedback">
            {% if feedback %}
                {% if correct %}
                    <p style="color:#008000;">Correct! Set at {{ progress }}</p>
                {% else %}
                    <p style="color:#A00000;"><span style="font-size:x-large;">{{ previous.q }}</span>  =  {{ previous.a }}</p>
                {% endif %}   
            {% endif %}
            </div>
            <div class="q_prompt"><p>{{ question.prompt }}</p></div>
            <div class="q_question"><p>{{ question.q }}</p></div>
            <div class="q_options">
                <table> <!-- Force all options to have the same width -->
                {% for choice in choices %}
                    <tr><td><a href="{% url 'hebrew_quiz:answer' choice.idx %}"><p>{{ choice.a }}</p></a></td></tr>
                {% endfor %}
                </table>
            </div>
        {% endif %}   
    </div>   
    {% if show_cat %}
        <div class="sidebar" style="border-bottom: 1px solid black;">    
            <p>Quiz Categories:</p>
            <table>
            {% for cat in categories %}
                {% if cat.done %}
                    <tr><td style="background-color:#008000; color:#FFFFFF">
                {% else %}
                    <tr><td>
                {% endif %}
                <a href="{% url 'hebrew_quiz:setCategory' cat.idx %}"><p>{{ cat.name }}</p></a></td></tr>
            {% endfor %}
            </table>
        </div>
    {% endif %}
    <div class="footer">
        <ul>
            {% if show_cat %}
                <li><a href="{% url 'hebrew_quiz:showCategories' 0 %}">Hide Categories</a></li>
            {% else %}
                <li><a href="{% url 'hebrew_quiz:showCategories' 1 %}">Show Categories</a></li>
            {% endif %}
            <li><a href="{% url 'hebrew_quiz:showHelp' 1 %}">Cheat</a></li>
        </ul>
    </div>
</div>
<p>Debug information:</p>
<p>{{ now }} | Moreh\hebrew_quiz\templates\hebrew_quiz\index.html</p>
{% for cat in categories %}
    <!--p>{{ cat }}</p-->
{% endfor %}
</body>
</html>